### ISSUE TITLE
how do i use an svg icon instead of pound in in show-on-hover anchor tag?

### ISSUE THREAD

**Issue by arshdkhn1** [JanitorTechnology/selfapi#25]
I want to use link svg icon instead of pound

**Comment by jankeromnes** [comment]
SelfAPI has no `show-on-hover` class, but it does add unique IDs to it's titles. I believe what you are looking for is this code: https://github.com/JanitorTechnology/janitor/blob/1339ee4ae712211a53d6a3f0eb4fee84eac4b994/static/js/janitor.js#L280-290

**Comment by arshdkhn1** [comment]
thanks @jankeromnes
